### ISSUE TITLE
Failure message reported by donut, in spite of creating the reports, in case of a test failures.

### ISSUE THREAD

**Issue by amitsha** [MagenTys/donut#11]
Below message is reported in the maven build, in case of test failures, even though donut report is generated successfully:

[ERROR] Failed to execute goal io.magentys:donut-maven-plugin:0.0.3:generate (execution) on project eas-module: Error Found: BUILD FAILED - Check Report For Details -> [Help 1]

**Comment by chdask** [comment]
Hi @amitsha. We are in purpose fail the build in case of a failed test because otherwise the build is marked as green which is misleading. Hope that makes sense. Check the donut-maven-plugin for more details.

**Comment by amitsha** [comment]
hi @chdask I've submitted a pull request for modifying the message to include the number of failed scenarios, when the number of failed scenarios > 0.
https://github.com/MagenTys/donut-maven-plugin/pull/2

Please review and merge.
