### ISSUE TITLE
Examples tables for Scenario outlines (<parameters> not rendering)

### ISSUE THREAD

**Issue by bjuric** [MagenTys/donut#40]
Examples tables are not being rendered in the report for non-expanded Scenario Outlines. I've created an [examples-tables](https://github.com/bjuric/donut/tree/examples-tables) branch on my fork to add them but the `<>` delimited parameters are lost in the report.

The branch contains an example [9a.json](https://github.com/bjuric/donut/blob/examples-tables/src/test/resources/samples-1/9a.json) JSON file used to test this feature. The following is a snippet of a step containing an outline parameter in that file..
```
            "keyword": "Given ",
            "name": "string 1 is \"<string 1>\""
```
I'd expect this to render as `Given string 1 is "<string1>"`
but instead get `Given string 1 is ""`

I've tried escaping the value in the HTMLProcessor class but I still get the same problem.

Here is a screenshot showing the examples tables rendering but the parameters not..

<img width="722" alt="examples-tables" src="https://user-images.githubusercontent.com/1369994/27548099-3a25bf76-5adb-11e7-9df0-a28e20075b0c.png">

**Comment by bjuric** [comment]
In general, the `<>` characters could appear anywhere in a gherkin feature. It just so happens that I'm raising it here as part of adding examples tables to the reports. I can take a closer look but wanted to raise it for tracking purposes.

**Comment by bjuric** [comment]
I discovered the missing `<>` problem to be caused by the unescaping of the entire report content after it is generated by mustache. 

Fix:
1. Use `{{{htmlElements}}}` in templates to prevent mustache from escaping the HTML
2. Remove the explicit unescaping of the report in the donut `TemplateEngine`
3. Escape the `<` and `>` chars in all data embedded into `htmlElements` in the donut `HTMLProcessor` class

**Comment by amitsha** [comment]
Hi @bjuric,

I can replicate the issue if we have <> in the Gherkin json file. But I'm not sure if that's a valid scenario.
The symbols <> are used to specify a parameter name in the feature file. And the cucumber reporter replaces the parameter with its corresponding value from the examples table. In the example below, the <table> parameter will be replaced by the corresponding values that could be legitimate or empty value.

And accordingly, the Gherkin JSON generated would have the values (without the symbols <>), so we won't have an issue in rendering the donut report.
  Scenario Outline: Compare a pivot table, found from a collection
	Then pivot table **"<table>"** should contain:
	  | colour | year | value |
	  | Red    | 2008 |   1   |

	Examples:
	  | table                  |
	  | pivot                  |
          |                            |
	  | pivotWithThRowHeaders  |
	  | pivotWithNestedCells   |

Regards,
Amit

**Comment by bjuric** [comment]
Hi Amit,

Good to hear from you.

What you are saying is correct when the outline is in expanded form (cucumber --expand option), see:
https://relishapp.com/cucumber/cucumber/docs/formatters/json-output-formatter#scenario-outline-expanded <https://relishapp.com/cucumber/cucumber/docs/formatters/json-output-formatter#scenario-outline-expanded> 

But the "non-expaned" form is also supported by Gherkin tools like Cucumber by default I believe (if you don't specify the --expand option): see:
https://relishapp.com/cucumber/cucumber/docs/formatters/json-output-formatter#scenario-outline <https://relishapp.com/cucumber/cucumber/docs/formatters/json-output-formatter#scenario-outline>

The JSON in the latter does not include substituted parameters or expanded scenarios like the former. I thought it good to support both variations.

Cheers,
Branko

**Comment by amitsha** [comment]
Hi Branko,

I think the non-expanded form is the default for cucumber ruby implementation. I'm more familiar with JVM and .net implementations, for which the default is expanded, that's why I wasn't familiar with this option :).

Looks like you've also provided the fix for this. I'll test it soon (Next week sometime) and merge.

Regards,
Amit

**Comment by amitsha** [comment]
Merged.
